top_srcdir   = /home/jiangxd/src/flashapp/httpd-2.2.22
top_builddir = /home/jiangxd/src/flashapp/httpd-2.2.22
srcdir       = /home/jiangxd/src/flashapp/httpd-2.2.22/os/unix
builddir     = /home/jiangxd/src/flashapp/httpd-2.2.22/os/unix
VPATH        = /home/jiangxd/src/flashapp/httpd-2.2.22/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
