top_srcdir   = /home/jiangxd/src/flashapp/httpd-2.2.22
top_builddir = /home/jiangxd/src/flashapp/httpd-2.2.22
srcdir       = /home/jiangxd/src/flashapp/httpd-2.2.22/modules/mappers
builddir     = /home/jiangxd/src/flashapp/httpd-2.2.22/modules/mappers
VPATH        = /home/jiangxd/src/flashapp/httpd-2.2.22/modules/mappers

include $(top_srcdir)/build/special.mk

