top_srcdir   = /home/jiangxd/src/flashapp/httpd-2.4.3
top_builddir = /home/jiangxd/src/flashapp/httpd-2.4.3
srcdir       = /home/jiangxd/src/flashapp/httpd-2.4.3/modules/flashapp
builddir     = /home/jiangxd/src/flashapp/httpd-2.4.3/modules/flashapp
VPATH        = /home/jiangxd/src/flashapp/httpd-2.4.3/modules/flashapp
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk

