top_srcdir   = /home/jiangxd/src/flashapp/httpd-2.2.22
top_builddir = /home/jiangxd/src/flashapp/httpd-2.2.22
srcdir       = /home/jiangxd/src/flashapp/httpd-2.2.22/modules
builddir     = /home/jiangxd/src/flashapp/httpd-2.2.22/modules
VPATH        = /home/jiangxd/src/flashapp/httpd-2.2.22/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

