top_srcdir   = /home/jiangxd/src/flashapp/httpd-2.2.22
top_builddir = /home/jiangxd/src/flashapp/httpd-2.2.22
srcdir       = /home/jiangxd/src/flashapp/httpd-2.2.22/modules/metadata
builddir     = /home/jiangxd/src/flashapp/httpd-2.2.22/modules/metadata
VPATH        = /home/jiangxd/src/flashapp/httpd-2.2.22/modules/metadata

include $(top_srcdir)/build/special.mk

