top_srcdir   = /home/jiangxd/src/flashapp/httpd-2.2.22
top_builddir = /home/jiangxd/src/flashapp/httpd-2.2.22
srcdir       = /home/jiangxd/src/flashapp/httpd-2.2.22/modules/loggers
builddir     = /home/jiangxd/src/flashapp/httpd-2.2.22/modules/loggers
VPATH        = /home/jiangxd/src/flashapp/httpd-2.2.22/modules/loggers

include $(top_srcdir)/build/special.mk

