top_srcdir   = /home/jiangxd/src/flashapp/httpd-2.2.22
top_builddir = /home/jiangxd/src/flashapp/httpd-2.2.22
srcdir       = /home/jiangxd/src/flashapp/httpd-2.2.22/server/mpm/worker
builddir     = /home/jiangxd/src/flashapp/httpd-2.2.22/server/mpm/worker
VPATH        = /home/jiangxd/src/flashapp/httpd-2.2.22/server/mpm/worker

LTLIBRARY_NAME    = libworker.la
LTLIBRARY_SOURCES = worker.c fdqueue.c pod.c

include $(top_srcdir)/build/ltlib.mk
