top_srcdir   = /home/jiangxd/src/flashapp/httpd-2.2.22
top_builddir = /home/jiangxd/src/flashapp/httpd-2.2.22
srcdir       = /home/jiangxd/src/flashapp/httpd-2.2.22/server/mpm/prefork
builddir     = /home/jiangxd/src/flashapp/httpd-2.2.22/server/mpm/prefork
VPATH        = /home/jiangxd/src/flashapp/httpd-2.2.22/server/mpm/prefork

LTLIBRARY_NAME    = libprefork.la
LTLIBRARY_SOURCES = prefork.c

include $(top_srcdir)/build/ltlib.mk
