top_srcdir   = /home/jiangxd/src/flashapp/httpd-2.2.22
top_builddir = /home/jiangxd/src/flashapp/httpd-2.2.22
srcdir       = /home/jiangxd/src/flashapp/httpd-2.2.22/modules/filters
builddir     = /home/jiangxd/src/flashapp/httpd-2.2.22/modules/filters
VPATH        = /home/jiangxd/src/flashapp/httpd-2.2.22/modules/filters

include $(top_srcdir)/build/special.mk

