top_srcdir   = /home/jiangxd/src/flashapp/httpd-2.2.22
top_builddir = /home/jiangxd/src/flashapp/httpd-2.2.22
srcdir       = /home/jiangxd/src/flashapp/httpd-2.2.22/srclib
builddir     = /home/jiangxd/src/flashapp/httpd-2.2.22/srclib
VPATH        = /home/jiangxd/src/flashapp/httpd-2.2.22/srclib

BUILD_SUBDIRS = $(AP_BUILD_SRCLIB_DIRS)
CLEAN_SUBDIRS = $(AP_CLEAN_SRCLIB_DIRS)

include $(top_builddir)/build/rules.mk
