top_srcdir   = /home/jiangxd/src/flashapp/httpd-2.2.22
top_builddir = /home/jiangxd/src/flashapp/httpd-2.2.22
srcdir       = /home/jiangxd/src/flashapp/httpd-2.2.22/modules/dav/main
builddir     = /home/jiangxd/src/flashapp/httpd-2.2.22/modules/dav/main
VPATH        = /home/jiangxd/src/flashapp/httpd-2.2.22/modules/dav/main
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
