top_srcdir   = /home/jiangxd/src/flashapp/httpd-2.2.22
top_builddir = /home/jiangxd/src/flashapp/httpd-2.2.22
srcdir       = /home/jiangxd/src/flashapp/httpd-2.2.22/modules/http
builddir     = /home/jiangxd/src/flashapp/httpd-2.2.22/modules/http
VPATH        = /home/jiangxd/src/flashapp/httpd-2.2.22/modules/http

include $(top_srcdir)/build/special.mk

